name: Deploy Feed Service

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SERVER_USER:
        required: true
      SERVER_ADDR:
        required: true
      ALIYUN_USERNAME:
        required: true
      ALIYUN_PASSWORD:
        required: true

jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - name: test Feed Service
        run: echo "Feed Service Test Successful!"
